#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.Clases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ES_SOCKS")]
	public partial class dcPmcDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertpmc_Plan(pmc_Plan instance);
    partial void Updatepmc_Plan(pmc_Plan instance);
    partial void Deletepmc_Plan(pmc_Plan instance);
    partial void Insertpmc_Semanas(pmc_Semanas instance);
    partial void Updatepmc_Semanas(pmc_Semanas instance);
    partial void Deletepmc_Semanas(pmc_Semanas instance);
    partial void Insertpmc_Solicitudes(pmc_Solicitudes instance);
    partial void Updatepmc_Solicitudes(pmc_Solicitudes instance);
    partial void Deletepmc_Solicitudes(pmc_Solicitudes instance);
    partial void Insertpmc_Entregas(pmc_Entregas instance);
    partial void Updatepmc_Entregas(pmc_Entregas instance);
    partial void Deletepmc_Entregas(pmc_Entregas instance);
    partial void Insertpmc_Mov_Bodega_Det(pmc_Mov_Bodega_Det instance);
    partial void Updatepmc_Mov_Bodega_Det(pmc_Mov_Bodega_Det instance);
    partial void Deletepmc_Mov_Bodega_Det(pmc_Mov_Bodega_Det instance);
    partial void Insertpmc_Mov_Bodega(pmc_Mov_Bodega instance);
    partial void Updatepmc_Mov_Bodega(pmc_Mov_Bodega instance);
    partial void Deletepmc_Mov_Bodega(pmc_Mov_Bodega instance);
    #endregion
		
		public dcPmcDataContext() : 
				base(global::Rmc.Properties.Settings.Default.ES_SOCKSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcPmcDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcPmcDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcPmcDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcPmcDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<pmc_Plan> pmc_Plan
		{
			get
			{
				return this.GetTable<pmc_Plan>();
			}
		}
		
		public System.Data.Linq.Table<pmc_Semanas> pmc_Semanas
		{
			get
			{
				return this.GetTable<pmc_Semanas>();
			}
		}
		
		public System.Data.Linq.Table<pmc_Solicitudes> pmc_Solicitudes
		{
			get
			{
				return this.GetTable<pmc_Solicitudes>();
			}
		}
		
		public System.Data.Linq.Table<pmc_Entregas> pmc_Entregas
		{
			get
			{
				return this.GetTable<pmc_Entregas>();
			}
		}
		
		public System.Data.Linq.Table<pmc_Mov_Bodega_Det> pmc_Mov_Bodega_Dets
		{
			get
			{
				return this.GetTable<pmc_Mov_Bodega_Det>();
			}
		}
		
		public System.Data.Linq.Table<pmc_Mov_Bodega> pmc_Mov_Bodegas
		{
			get
			{
				return this.GetTable<pmc_Mov_Bodega>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_pmc_Solicitudes_CRUD")]
		public ISingleResult<usp_pmc_Solicitudes_CRUDResult> usp_pmc_Solicitudes_CRUD([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sol_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(7)")] string sol_semana, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SACA", DbType="VarChar(8)")] string sACA, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string sol_item, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string sol_item_desv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sol_cant, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sol_desv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sol_sobreconsumo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string sol_localidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sol_ID, sol_semana, sACA, sol_item, sol_item_desv, sol_cant, sol_desv, sol_sobreconsumo, sol_localidad, accion);
			return ((ISingleResult<usp_pmc_Solicitudes_CRUDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Plan")]
	public partial class pmc_Plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pla_semana;
		
		private string _pla_SACA;
		
		private string _pla_item;
		
		private string _pla_silueta;
		
		private string _pla_estilo;
		
		private string _pla_talla;
		
		private int _pla_cantidad;
		
		private System.Nullable<int> _pla_sobrantes;
		
		private System.Nullable<int> _pla_estado;
		
		private string _pla_item_desv;
		
		private System.DateTime _pla_FH_crea;
		
		private string _pla_usuario_crea;
		
		private string _sol_item_desv;
		
		private System.Nullable<System.DateTime> _pla_FH_mod;
		
		private string _pla_usuario_mod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpla_semanaChanging(string value);
    partial void Onpla_semanaChanged();
    partial void Onpla_SACAChanging(string value);
    partial void Onpla_SACAChanged();
    partial void Onpla_itemChanging(string value);
    partial void Onpla_itemChanged();
    partial void Onpla_siluetaChanging(string value);
    partial void Onpla_siluetaChanged();
    partial void Onpla_estiloChanging(string value);
    partial void Onpla_estiloChanged();
    partial void Onpla_tallaChanging(string value);
    partial void Onpla_tallaChanged();
    partial void Onpla_cantidadChanging(int value);
    partial void Onpla_cantidadChanged();
    partial void Onpla_sobrantesChanging(System.Nullable<int> value);
    partial void Onpla_sobrantesChanged();
    partial void Onpla_estadoChanging(System.Nullable<int> value);
    partial void Onpla_estadoChanged();
    partial void Onpla_item_desvChanging(string value);
    partial void Onpla_item_desvChanged();
    partial void Onpla_FH_creaChanging(System.DateTime value);
    partial void Onpla_FH_creaChanged();
    partial void Onpla_usuario_creaChanging(string value);
    partial void Onpla_usuario_creaChanged();
    partial void Onsol_item_desvChanging(string value);
    partial void Onsol_item_desvChanged();
    partial void Onpla_FH_modChanging(System.Nullable<System.DateTime> value);
    partial void Onpla_FH_modChanged();
    partial void Onpla_usuario_modChanging(string value);
    partial void Onpla_usuario_modChanged();
    #endregion
		
		public pmc_Plan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_semana", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pla_semana
		{
			get
			{
				return this._pla_semana;
			}
			set
			{
				if ((this._pla_semana != value))
				{
					this.Onpla_semanaChanging(value);
					this.SendPropertyChanging();
					this._pla_semana = value;
					this.SendPropertyChanged("pla_semana");
					this.Onpla_semanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_SACA", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pla_SACA
		{
			get
			{
				return this._pla_SACA;
			}
			set
			{
				if ((this._pla_SACA != value))
				{
					this.Onpla_SACAChanging(value);
					this.SendPropertyChanging();
					this._pla_SACA = value;
					this.SendPropertyChanged("pla_SACA");
					this.Onpla_SACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_item", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pla_item
		{
			get
			{
				return this._pla_item;
			}
			set
			{
				if ((this._pla_item != value))
				{
					this.Onpla_itemChanging(value);
					this.SendPropertyChanging();
					this._pla_item = value;
					this.SendPropertyChanged("pla_item");
					this.Onpla_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_silueta", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string pla_silueta
		{
			get
			{
				return this._pla_silueta;
			}
			set
			{
				if ((this._pla_silueta != value))
				{
					this.Onpla_siluetaChanging(value);
					this.SendPropertyChanging();
					this._pla_silueta = value;
					this.SendPropertyChanged("pla_silueta");
					this.Onpla_siluetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_estilo", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string pla_estilo
		{
			get
			{
				return this._pla_estilo;
			}
			set
			{
				if ((this._pla_estilo != value))
				{
					this.Onpla_estiloChanging(value);
					this.SendPropertyChanging();
					this._pla_estilo = value;
					this.SendPropertyChanged("pla_estilo");
					this.Onpla_estiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_talla", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string pla_talla
		{
			get
			{
				return this._pla_talla;
			}
			set
			{
				if ((this._pla_talla != value))
				{
					this.Onpla_tallaChanging(value);
					this.SendPropertyChanging();
					this._pla_talla = value;
					this.SendPropertyChanged("pla_talla");
					this.Onpla_tallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_cantidad", DbType="Int NOT NULL")]
		public int pla_cantidad
		{
			get
			{
				return this._pla_cantidad;
			}
			set
			{
				if ((this._pla_cantidad != value))
				{
					this.Onpla_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pla_cantidad = value;
					this.SendPropertyChanged("pla_cantidad");
					this.Onpla_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_sobrantes", DbType="Int")]
		public System.Nullable<int> pla_sobrantes
		{
			get
			{
				return this._pla_sobrantes;
			}
			set
			{
				if ((this._pla_sobrantes != value))
				{
					this.Onpla_sobrantesChanging(value);
					this.SendPropertyChanging();
					this._pla_sobrantes = value;
					this.SendPropertyChanged("pla_sobrantes");
					this.Onpla_sobrantesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_estado", DbType="Int")]
		public System.Nullable<int> pla_estado
		{
			get
			{
				return this._pla_estado;
			}
			set
			{
				if ((this._pla_estado != value))
				{
					this.Onpla_estadoChanging(value);
					this.SendPropertyChanging();
					this._pla_estado = value;
					this.SendPropertyChanged("pla_estado");
					this.Onpla_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_item_desv", DbType="VarChar(25)")]
		public string pla_item_desv
		{
			get
			{
				return this._pla_item_desv;
			}
			set
			{
				if ((this._pla_item_desv != value))
				{
					this.Onpla_item_desvChanging(value);
					this.SendPropertyChanging();
					this._pla_item_desv = value;
					this.SendPropertyChanged("pla_item_desv");
					this.Onpla_item_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_FH_crea", DbType="DateTime NOT NULL")]
		public System.DateTime pla_FH_crea
		{
			get
			{
				return this._pla_FH_crea;
			}
			set
			{
				if ((this._pla_FH_crea != value))
				{
					this.Onpla_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._pla_FH_crea = value;
					this.SendPropertyChanged("pla_FH_crea");
					this.Onpla_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_usuario_crea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string pla_usuario_crea
		{
			get
			{
				return this._pla_usuario_crea;
			}
			set
			{
				if ((this._pla_usuario_crea != value))
				{
					this.Onpla_usuario_creaChanging(value);
					this.SendPropertyChanging();
					this._pla_usuario_crea = value;
					this.SendPropertyChanged("pla_usuario_crea");
					this.Onpla_usuario_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_item_desv", DbType="VarChar(25)")]
		public string sol_item_desv
		{
			get
			{
				return this._sol_item_desv;
			}
			set
			{
				if ((this._sol_item_desv != value))
				{
					this.Onsol_item_desvChanging(value);
					this.SendPropertyChanging();
					this._sol_item_desv = value;
					this.SendPropertyChanged("sol_item_desv");
					this.Onsol_item_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_FH_mod", DbType="DateTime")]
		public System.Nullable<System.DateTime> pla_FH_mod
		{
			get
			{
				return this._pla_FH_mod;
			}
			set
			{
				if ((this._pla_FH_mod != value))
				{
					this.Onpla_FH_modChanging(value);
					this.SendPropertyChanging();
					this._pla_FH_mod = value;
					this.SendPropertyChanged("pla_FH_mod");
					this.Onpla_FH_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pla_usuario_mod", DbType="VarChar(25)")]
		public string pla_usuario_mod
		{
			get
			{
				return this._pla_usuario_mod;
			}
			set
			{
				if ((this._pla_usuario_mod != value))
				{
					this.Onpla_usuario_modChanging(value);
					this.SendPropertyChanging();
					this._pla_usuario_mod = value;
					this.SendPropertyChanged("pla_usuario_mod");
					this.Onpla_usuario_modChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Semanas")]
	public partial class pmc_Semanas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _sem_ID;
		
		private System.DateTime _sem_FH_crea;
		
		private string _sem_usuario_crea;
		
		private System.Nullable<System.DateTime> _sem_FH_mod;
		
		private string _sem_usuario_mod;
		
		private bool _sem_estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsem_IDChanging(string value);
    partial void Onsem_IDChanged();
    partial void Onsem_FH_creaChanging(System.DateTime value);
    partial void Onsem_FH_creaChanged();
    partial void Onsem_usuario_creaChanging(string value);
    partial void Onsem_usuario_creaChanged();
    partial void Onsem_FH_modChanging(System.Nullable<System.DateTime> value);
    partial void Onsem_FH_modChanged();
    partial void Onsem_usuario_modChanging(string value);
    partial void Onsem_usuario_modChanged();
    partial void Onsem_estadoChanging(bool value);
    partial void Onsem_estadoChanged();
    #endregion
		
		public pmc_Semanas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string sem_ID
		{
			get
			{
				return this._sem_ID;
			}
			set
			{
				if ((this._sem_ID != value))
				{
					this.Onsem_IDChanging(value);
					this.SendPropertyChanging();
					this._sem_ID = value;
					this.SendPropertyChanged("sem_ID");
					this.Onsem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_FH_crea", DbType="DateTime NOT NULL")]
		public System.DateTime sem_FH_crea
		{
			get
			{
				return this._sem_FH_crea;
			}
			set
			{
				if ((this._sem_FH_crea != value))
				{
					this.Onsem_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._sem_FH_crea = value;
					this.SendPropertyChanged("sem_FH_crea");
					this.Onsem_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_usuario_crea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string sem_usuario_crea
		{
			get
			{
				return this._sem_usuario_crea;
			}
			set
			{
				if ((this._sem_usuario_crea != value))
				{
					this.Onsem_usuario_creaChanging(value);
					this.SendPropertyChanging();
					this._sem_usuario_crea = value;
					this.SendPropertyChanged("sem_usuario_crea");
					this.Onsem_usuario_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_FH_mod", DbType="DateTime")]
		public System.Nullable<System.DateTime> sem_FH_mod
		{
			get
			{
				return this._sem_FH_mod;
			}
			set
			{
				if ((this._sem_FH_mod != value))
				{
					this.Onsem_FH_modChanging(value);
					this.SendPropertyChanging();
					this._sem_FH_mod = value;
					this.SendPropertyChanged("sem_FH_mod");
					this.Onsem_FH_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_usuario_mod", DbType="VarChar(25)")]
		public string sem_usuario_mod
		{
			get
			{
				return this._sem_usuario_mod;
			}
			set
			{
				if ((this._sem_usuario_mod != value))
				{
					this.Onsem_usuario_modChanging(value);
					this.SendPropertyChanging();
					this._sem_usuario_mod = value;
					this.SendPropertyChanged("sem_usuario_mod");
					this.Onsem_usuario_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem_estado", DbType="Bit NOT NULL")]
		public bool sem_estado
		{
			get
			{
				return this._sem_estado;
			}
			set
			{
				if ((this._sem_estado != value))
				{
					this.Onsem_estadoChanging(value);
					this.SendPropertyChanging();
					this._sem_estado = value;
					this.SendPropertyChanged("sem_estado");
					this.Onsem_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Solicitudes")]
	public partial class pmc_Solicitudes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sol_ID;
		
		private string _sol_semana;
		
		private string _sol_SACA;
		
		private string _sol_item;
		
		private string _sol_item_desv;
		
		private int _sol_cant;
		
		private bool _sol_desv;
		
		private System.DateTime _sol_FH_crea;
		
		private System.Nullable<System.DateTime> _sol_FH_modifica;
		
		private string _sol_usuario_crea;
		
		private string _sol_usuario_modifica;
		
		private System.Nullable<int> _sol_cant_entregada;
		
		private string _sol_usuario_entrega;
		
		private System.Nullable<System.DateTime> _sol_FH_entrega;
		
		private System.Nullable<int> _sol_estado;
		
		private System.Nullable<bool> _sol_salida;
		
		private System.Nullable<bool> _sol_sobreconsumo;
		
		private string _sol_localidad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsol_IDChanging(int value);
    partial void Onsol_IDChanged();
    partial void Onsol_semanaChanging(string value);
    partial void Onsol_semanaChanged();
    partial void Onsol_SACAChanging(string value);
    partial void Onsol_SACAChanged();
    partial void Onsol_itemChanging(string value);
    partial void Onsol_itemChanged();
    partial void Onsol_item_desvChanging(string value);
    partial void Onsol_item_desvChanged();
    partial void Onsol_cantChanging(int value);
    partial void Onsol_cantChanged();
    partial void Onsol_desvChanging(bool value);
    partial void Onsol_desvChanged();
    partial void Onsol_FH_creaChanging(System.DateTime value);
    partial void Onsol_FH_creaChanged();
    partial void Onsol_FH_modificaChanging(System.Nullable<System.DateTime> value);
    partial void Onsol_FH_modificaChanged();
    partial void Onsol_usuario_creaChanging(string value);
    partial void Onsol_usuario_creaChanged();
    partial void Onsol_usuario_modificaChanging(string value);
    partial void Onsol_usuario_modificaChanged();
    partial void Onsol_cant_entregadaChanging(System.Nullable<int> value);
    partial void Onsol_cant_entregadaChanged();
    partial void Onsol_usuario_entregaChanging(string value);
    partial void Onsol_usuario_entregaChanged();
    partial void Onsol_FH_entregaChanging(System.Nullable<System.DateTime> value);
    partial void Onsol_FH_entregaChanged();
    partial void Onsol_estadoChanging(System.Nullable<int> value);
    partial void Onsol_estadoChanged();
    partial void Onsol_salidaChanging(System.Nullable<bool> value);
    partial void Onsol_salidaChanged();
    partial void Onsol_sobreconsumoChanging(System.Nullable<bool> value);
    partial void Onsol_sobreconsumoChanged();
    partial void Onsol_localidadChanging(string value);
    partial void Onsol_localidadChanged();
    #endregion
		
		public pmc_Solicitudes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sol_ID
		{
			get
			{
				return this._sol_ID;
			}
			set
			{
				if ((this._sol_ID != value))
				{
					this.Onsol_IDChanging(value);
					this.SendPropertyChanging();
					this._sol_ID = value;
					this.SendPropertyChanged("sol_ID");
					this.Onsol_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_semana", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string sol_semana
		{
			get
			{
				return this._sol_semana;
			}
			set
			{
				if ((this._sol_semana != value))
				{
					this.Onsol_semanaChanging(value);
					this.SendPropertyChanging();
					this._sol_semana = value;
					this.SendPropertyChanged("sol_semana");
					this.Onsol_semanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_SACA", DbType="VarChar(8)")]
		public string sol_SACA
		{
			get
			{
				return this._sol_SACA;
			}
			set
			{
				if ((this._sol_SACA != value))
				{
					this.Onsol_SACAChanging(value);
					this.SendPropertyChanging();
					this._sol_SACA = value;
					this.SendPropertyChanged("sol_SACA");
					this.Onsol_SACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_item", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string sol_item
		{
			get
			{
				return this._sol_item;
			}
			set
			{
				if ((this._sol_item != value))
				{
					this.Onsol_itemChanging(value);
					this.SendPropertyChanging();
					this._sol_item = value;
					this.SendPropertyChanged("sol_item");
					this.Onsol_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_item_desv", DbType="VarChar(25)")]
		public string sol_item_desv
		{
			get
			{
				return this._sol_item_desv;
			}
			set
			{
				if ((this._sol_item_desv != value))
				{
					this.Onsol_item_desvChanging(value);
					this.SendPropertyChanging();
					this._sol_item_desv = value;
					this.SendPropertyChanged("sol_item_desv");
					this.Onsol_item_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_cant", DbType="Int NOT NULL")]
		public int sol_cant
		{
			get
			{
				return this._sol_cant;
			}
			set
			{
				if ((this._sol_cant != value))
				{
					this.Onsol_cantChanging(value);
					this.SendPropertyChanging();
					this._sol_cant = value;
					this.SendPropertyChanged("sol_cant");
					this.Onsol_cantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_desv", DbType="Bit NOT NULL")]
		public bool sol_desv
		{
			get
			{
				return this._sol_desv;
			}
			set
			{
				if ((this._sol_desv != value))
				{
					this.Onsol_desvChanging(value);
					this.SendPropertyChanging();
					this._sol_desv = value;
					this.SendPropertyChanged("sol_desv");
					this.Onsol_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_FH_crea", DbType="DateTime NOT NULL")]
		public System.DateTime sol_FH_crea
		{
			get
			{
				return this._sol_FH_crea;
			}
			set
			{
				if ((this._sol_FH_crea != value))
				{
					this.Onsol_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._sol_FH_crea = value;
					this.SendPropertyChanged("sol_FH_crea");
					this.Onsol_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_FH_modifica", DbType="DateTime")]
		public System.Nullable<System.DateTime> sol_FH_modifica
		{
			get
			{
				return this._sol_FH_modifica;
			}
			set
			{
				if ((this._sol_FH_modifica != value))
				{
					this.Onsol_FH_modificaChanging(value);
					this.SendPropertyChanging();
					this._sol_FH_modifica = value;
					this.SendPropertyChanged("sol_FH_modifica");
					this.Onsol_FH_modificaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_usuario_crea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string sol_usuario_crea
		{
			get
			{
				return this._sol_usuario_crea;
			}
			set
			{
				if ((this._sol_usuario_crea != value))
				{
					this.Onsol_usuario_creaChanging(value);
					this.SendPropertyChanging();
					this._sol_usuario_crea = value;
					this.SendPropertyChanged("sol_usuario_crea");
					this.Onsol_usuario_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_usuario_modifica", DbType="VarChar(25)")]
		public string sol_usuario_modifica
		{
			get
			{
				return this._sol_usuario_modifica;
			}
			set
			{
				if ((this._sol_usuario_modifica != value))
				{
					this.Onsol_usuario_modificaChanging(value);
					this.SendPropertyChanging();
					this._sol_usuario_modifica = value;
					this.SendPropertyChanged("sol_usuario_modifica");
					this.Onsol_usuario_modificaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_cant_entregada", DbType="Int")]
		public System.Nullable<int> sol_cant_entregada
		{
			get
			{
				return this._sol_cant_entregada;
			}
			set
			{
				if ((this._sol_cant_entregada != value))
				{
					this.Onsol_cant_entregadaChanging(value);
					this.SendPropertyChanging();
					this._sol_cant_entregada = value;
					this.SendPropertyChanged("sol_cant_entregada");
					this.Onsol_cant_entregadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_usuario_entrega", DbType="VarChar(25)")]
		public string sol_usuario_entrega
		{
			get
			{
				return this._sol_usuario_entrega;
			}
			set
			{
				if ((this._sol_usuario_entrega != value))
				{
					this.Onsol_usuario_entregaChanging(value);
					this.SendPropertyChanging();
					this._sol_usuario_entrega = value;
					this.SendPropertyChanged("sol_usuario_entrega");
					this.Onsol_usuario_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_FH_entrega", DbType="DateTime")]
		public System.Nullable<System.DateTime> sol_FH_entrega
		{
			get
			{
				return this._sol_FH_entrega;
			}
			set
			{
				if ((this._sol_FH_entrega != value))
				{
					this.Onsol_FH_entregaChanging(value);
					this.SendPropertyChanging();
					this._sol_FH_entrega = value;
					this.SendPropertyChanged("sol_FH_entrega");
					this.Onsol_FH_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_estado", DbType="Int")]
		public System.Nullable<int> sol_estado
		{
			get
			{
				return this._sol_estado;
			}
			set
			{
				if ((this._sol_estado != value))
				{
					this.Onsol_estadoChanging(value);
					this.SendPropertyChanging();
					this._sol_estado = value;
					this.SendPropertyChanged("sol_estado");
					this.Onsol_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_salida", DbType="Bit")]
		public System.Nullable<bool> sol_salida
		{
			get
			{
				return this._sol_salida;
			}
			set
			{
				if ((this._sol_salida != value))
				{
					this.Onsol_salidaChanging(value);
					this.SendPropertyChanging();
					this._sol_salida = value;
					this.SendPropertyChanged("sol_salida");
					this.Onsol_salidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_sobreconsumo", DbType="Bit")]
		public System.Nullable<bool> sol_sobreconsumo
		{
			get
			{
				return this._sol_sobreconsumo;
			}
			set
			{
				if ((this._sol_sobreconsumo != value))
				{
					this.Onsol_sobreconsumoChanging(value);
					this.SendPropertyChanging();
					this._sol_sobreconsumo = value;
					this.SendPropertyChanged("sol_sobreconsumo");
					this.Onsol_sobreconsumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sol_localidad", DbType="VarChar(50)")]
		public string sol_localidad
		{
			get
			{
				return this._sol_localidad;
			}
			set
			{
				if ((this._sol_localidad != value))
				{
					this.Onsol_localidadChanging(value);
					this.SendPropertyChanging();
					this._sol_localidad = value;
					this.SendPropertyChanged("sol_localidad");
					this.Onsol_localidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Entregas")]
	public partial class pmc_Entregas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ent_ID;
		
		private int _ent_sol_ID;
		
		private System.Nullable<System.DateTime> _ent_FH_crea;
		
		private string _ent_usuario_crea;
		
		private System.Nullable<int> _ent_num_reporte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onent_IDChanging(int value);
    partial void Onent_IDChanged();
    partial void Onent_sol_IDChanging(int value);
    partial void Onent_sol_IDChanged();
    partial void Onent_FH_creaChanging(System.Nullable<System.DateTime> value);
    partial void Onent_FH_creaChanged();
    partial void Onent_usuario_creaChanging(string value);
    partial void Onent_usuario_creaChanged();
    partial void Onent_num_reporteChanging(System.Nullable<int> value);
    partial void Onent_num_reporteChanged();
    #endregion
		
		public pmc_Entregas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ent_ID
		{
			get
			{
				return this._ent_ID;
			}
			set
			{
				if ((this._ent_ID != value))
				{
					this.Onent_IDChanging(value);
					this.SendPropertyChanging();
					this._ent_ID = value;
					this.SendPropertyChanged("ent_ID");
					this.Onent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent_sol_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ent_sol_ID
		{
			get
			{
				return this._ent_sol_ID;
			}
			set
			{
				if ((this._ent_sol_ID != value))
				{
					this.Onent_sol_IDChanging(value);
					this.SendPropertyChanging();
					this._ent_sol_ID = value;
					this.SendPropertyChanged("ent_sol_ID");
					this.Onent_sol_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent_FH_crea", DbType="DateTime")]
		public System.Nullable<System.DateTime> ent_FH_crea
		{
			get
			{
				return this._ent_FH_crea;
			}
			set
			{
				if ((this._ent_FH_crea != value))
				{
					this.Onent_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._ent_FH_crea = value;
					this.SendPropertyChanged("ent_FH_crea");
					this.Onent_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent_usuario_crea", DbType="VarChar(25)")]
		public string ent_usuario_crea
		{
			get
			{
				return this._ent_usuario_crea;
			}
			set
			{
				if ((this._ent_usuario_crea != value))
				{
					this.Onent_usuario_creaChanging(value);
					this.SendPropertyChanging();
					this._ent_usuario_crea = value;
					this.SendPropertyChanged("ent_usuario_crea");
					this.Onent_usuario_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ent_num_reporte", DbType="Int")]
		public System.Nullable<int> ent_num_reporte
		{
			get
			{
				return this._ent_num_reporte;
			}
			set
			{
				if ((this._ent_num_reporte != value))
				{
					this.Onent_num_reporteChanging(value);
					this.SendPropertyChanging();
					this._ent_num_reporte = value;
					this.SendPropertyChanged("ent_num_reporte");
					this.Onent_num_reporteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Mov_Bodega_Det")]
	public partial class pmc_Mov_Bodega_Det : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mov_det_ID;
		
		private string _mov_det_semana;
		
		private string _mov_det_item;
		
		private string _mov_det_desv;
		
		private System.Nullable<int> _mov_det_cant;
		
		private System.Nullable<int> _mov_det_cant_desv;
		
		private System.Nullable<System.DateTime> _mov_det_FH_crea;
		
		private string _mov_det_usuario;
		
		private System.Nullable<System.DateTime> _mov_det_FH_mod;
		
		private string _mov_det_usuario_mod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmov_det_IDChanging(int value);
    partial void Onmov_det_IDChanged();
    partial void Onmov_det_semanaChanging(string value);
    partial void Onmov_det_semanaChanged();
    partial void Onmov_det_itemChanging(string value);
    partial void Onmov_det_itemChanged();
    partial void Onmov_det_desvChanging(string value);
    partial void Onmov_det_desvChanged();
    partial void Onmov_det_cantChanging(System.Nullable<int> value);
    partial void Onmov_det_cantChanged();
    partial void Onmov_det_cant_desvChanging(System.Nullable<int> value);
    partial void Onmov_det_cant_desvChanged();
    partial void Onmov_det_FH_creaChanging(System.Nullable<System.DateTime> value);
    partial void Onmov_det_FH_creaChanged();
    partial void Onmov_det_usuarioChanging(string value);
    partial void Onmov_det_usuarioChanged();
    partial void Onmov_det_FH_modChanging(System.Nullable<System.DateTime> value);
    partial void Onmov_det_FH_modChanged();
    partial void Onmov_det_usuario_modChanging(string value);
    partial void Onmov_det_usuario_modChanged();
    #endregion
		
		public pmc_Mov_Bodega_Det()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mov_det_ID
		{
			get
			{
				return this._mov_det_ID;
			}
			set
			{
				if ((this._mov_det_ID != value))
				{
					this.Onmov_det_IDChanging(value);
					this.SendPropertyChanging();
					this._mov_det_ID = value;
					this.SendPropertyChanged("mov_det_ID");
					this.Onmov_det_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_semana", DbType="VarChar(7)")]
		public string mov_det_semana
		{
			get
			{
				return this._mov_det_semana;
			}
			set
			{
				if ((this._mov_det_semana != value))
				{
					this.Onmov_det_semanaChanging(value);
					this.SendPropertyChanging();
					this._mov_det_semana = value;
					this.SendPropertyChanged("mov_det_semana");
					this.Onmov_det_semanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_item", DbType="VarChar(25)")]
		public string mov_det_item
		{
			get
			{
				return this._mov_det_item;
			}
			set
			{
				if ((this._mov_det_item != value))
				{
					this.Onmov_det_itemChanging(value);
					this.SendPropertyChanging();
					this._mov_det_item = value;
					this.SendPropertyChanged("mov_det_item");
					this.Onmov_det_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_desv", DbType="VarChar(25)")]
		public string mov_det_desv
		{
			get
			{
				return this._mov_det_desv;
			}
			set
			{
				if ((this._mov_det_desv != value))
				{
					this.Onmov_det_desvChanging(value);
					this.SendPropertyChanging();
					this._mov_det_desv = value;
					this.SendPropertyChanged("mov_det_desv");
					this.Onmov_det_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_cant", DbType="Int")]
		public System.Nullable<int> mov_det_cant
		{
			get
			{
				return this._mov_det_cant;
			}
			set
			{
				if ((this._mov_det_cant != value))
				{
					this.Onmov_det_cantChanging(value);
					this.SendPropertyChanging();
					this._mov_det_cant = value;
					this.SendPropertyChanged("mov_det_cant");
					this.Onmov_det_cantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_cant_desv", DbType="Int")]
		public System.Nullable<int> mov_det_cant_desv
		{
			get
			{
				return this._mov_det_cant_desv;
			}
			set
			{
				if ((this._mov_det_cant_desv != value))
				{
					this.Onmov_det_cant_desvChanging(value);
					this.SendPropertyChanging();
					this._mov_det_cant_desv = value;
					this.SendPropertyChanged("mov_det_cant_desv");
					this.Onmov_det_cant_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_FH_crea", DbType="DateTime")]
		public System.Nullable<System.DateTime> mov_det_FH_crea
		{
			get
			{
				return this._mov_det_FH_crea;
			}
			set
			{
				if ((this._mov_det_FH_crea != value))
				{
					this.Onmov_det_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._mov_det_FH_crea = value;
					this.SendPropertyChanged("mov_det_FH_crea");
					this.Onmov_det_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_usuario", DbType="VarChar(25)")]
		public string mov_det_usuario
		{
			get
			{
				return this._mov_det_usuario;
			}
			set
			{
				if ((this._mov_det_usuario != value))
				{
					this.Onmov_det_usuarioChanging(value);
					this.SendPropertyChanging();
					this._mov_det_usuario = value;
					this.SendPropertyChanged("mov_det_usuario");
					this.Onmov_det_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_FH_mod", DbType="DateTime")]
		public System.Nullable<System.DateTime> mov_det_FH_mod
		{
			get
			{
				return this._mov_det_FH_mod;
			}
			set
			{
				if ((this._mov_det_FH_mod != value))
				{
					this.Onmov_det_FH_modChanging(value);
					this.SendPropertyChanging();
					this._mov_det_FH_mod = value;
					this.SendPropertyChanged("mov_det_FH_mod");
					this.Onmov_det_FH_modChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_det_usuario_mod", DbType="VarChar(25)")]
		public string mov_det_usuario_mod
		{
			get
			{
				return this._mov_det_usuario_mod;
			}
			set
			{
				if ((this._mov_det_usuario_mod != value))
				{
					this.Onmov_det_usuario_modChanging(value);
					this.SendPropertyChanging();
					this._mov_det_usuario_mod = value;
					this.SendPropertyChanged("mov_det_usuario_mod");
					this.Onmov_det_usuario_modChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pmc_Mov_Bodega")]
	public partial class pmc_Mov_Bodega : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mov_semana;
		
		private string _mov_item;
		
		private string _mov_item_desv;
		
		private System.Nullable<int> _mov_cantidad;
		
		private System.Nullable<int> _mov_cantidad_vieja;
		
		private System.Nullable<int> _mov_cantidad_vieja_desc;
		
		private System.Nullable<System.DateTime> _mov_FH_crea;
		
		private string _mov_usuario_crea;
		
		private System.Nullable<int> _mov_orden;
		
		private System.Nullable<System.DateTime> _mov_FH_modificacion;
		
		private string _mov_usuario_modificacion;
		
		private System.Nullable<int> _mov_estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmov_semanaChanging(string value);
    partial void Onmov_semanaChanged();
    partial void Onmov_itemChanging(string value);
    partial void Onmov_itemChanged();
    partial void Onmov_item_desvChanging(string value);
    partial void Onmov_item_desvChanged();
    partial void Onmov_cantidadChanging(System.Nullable<int> value);
    partial void Onmov_cantidadChanged();
    partial void Onmov_cantidad_viejaChanging(System.Nullable<int> value);
    partial void Onmov_cantidad_viejaChanged();
    partial void Onmov_cantidad_vieja_descChanging(System.Nullable<int> value);
    partial void Onmov_cantidad_vieja_descChanged();
    partial void Onmov_FH_creaChanging(System.Nullable<System.DateTime> value);
    partial void Onmov_FH_creaChanged();
    partial void Onmov_usuario_creaChanging(string value);
    partial void Onmov_usuario_creaChanged();
    partial void Onmov_ordenChanging(System.Nullable<int> value);
    partial void Onmov_ordenChanged();
    partial void Onmov_FH_modificacionChanging(System.Nullable<System.DateTime> value);
    partial void Onmov_FH_modificacionChanged();
    partial void Onmov_usuario_modificacionChanging(string value);
    partial void Onmov_usuario_modificacionChanged();
    partial void Onmov_estadoChanging(System.Nullable<int> value);
    partial void Onmov_estadoChanged();
    #endregion
		
		public pmc_Mov_Bodega()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_semana", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mov_semana
		{
			get
			{
				return this._mov_semana;
			}
			set
			{
				if ((this._mov_semana != value))
				{
					this.Onmov_semanaChanging(value);
					this.SendPropertyChanging();
					this._mov_semana = value;
					this.SendPropertyChanged("mov_semana");
					this.Onmov_semanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_item", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mov_item
		{
			get
			{
				return this._mov_item;
			}
			set
			{
				if ((this._mov_item != value))
				{
					this.Onmov_itemChanging(value);
					this.SendPropertyChanging();
					this._mov_item = value;
					this.SendPropertyChanged("mov_item");
					this.Onmov_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_item_desv", DbType="VarChar(25)")]
		public string mov_item_desv
		{
			get
			{
				return this._mov_item_desv;
			}
			set
			{
				if ((this._mov_item_desv != value))
				{
					this.Onmov_item_desvChanging(value);
					this.SendPropertyChanging();
					this._mov_item_desv = value;
					this.SendPropertyChanged("mov_item_desv");
					this.Onmov_item_desvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_cantidad", DbType="Int")]
		public System.Nullable<int> mov_cantidad
		{
			get
			{
				return this._mov_cantidad;
			}
			set
			{
				if ((this._mov_cantidad != value))
				{
					this.Onmov_cantidadChanging(value);
					this.SendPropertyChanging();
					this._mov_cantidad = value;
					this.SendPropertyChanged("mov_cantidad");
					this.Onmov_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_cantidad_vieja", DbType="Int")]
		public System.Nullable<int> mov_cantidad_vieja
		{
			get
			{
				return this._mov_cantidad_vieja;
			}
			set
			{
				if ((this._mov_cantidad_vieja != value))
				{
					this.Onmov_cantidad_viejaChanging(value);
					this.SendPropertyChanging();
					this._mov_cantidad_vieja = value;
					this.SendPropertyChanged("mov_cantidad_vieja");
					this.Onmov_cantidad_viejaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_cantidad_vieja_desc", DbType="Int")]
		public System.Nullable<int> mov_cantidad_vieja_desc
		{
			get
			{
				return this._mov_cantidad_vieja_desc;
			}
			set
			{
				if ((this._mov_cantidad_vieja_desc != value))
				{
					this.Onmov_cantidad_vieja_descChanging(value);
					this.SendPropertyChanging();
					this._mov_cantidad_vieja_desc = value;
					this.SendPropertyChanged("mov_cantidad_vieja_desc");
					this.Onmov_cantidad_vieja_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_FH_crea", DbType="DateTime")]
		public System.Nullable<System.DateTime> mov_FH_crea
		{
			get
			{
				return this._mov_FH_crea;
			}
			set
			{
				if ((this._mov_FH_crea != value))
				{
					this.Onmov_FH_creaChanging(value);
					this.SendPropertyChanging();
					this._mov_FH_crea = value;
					this.SendPropertyChanged("mov_FH_crea");
					this.Onmov_FH_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_usuario_crea", DbType="VarChar(25)")]
		public string mov_usuario_crea
		{
			get
			{
				return this._mov_usuario_crea;
			}
			set
			{
				if ((this._mov_usuario_crea != value))
				{
					this.Onmov_usuario_creaChanging(value);
					this.SendPropertyChanging();
					this._mov_usuario_crea = value;
					this.SendPropertyChanged("mov_usuario_crea");
					this.Onmov_usuario_creaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_orden", DbType="Int")]
		public System.Nullable<int> mov_orden
		{
			get
			{
				return this._mov_orden;
			}
			set
			{
				if ((this._mov_orden != value))
				{
					this.Onmov_ordenChanging(value);
					this.SendPropertyChanging();
					this._mov_orden = value;
					this.SendPropertyChanged("mov_orden");
					this.Onmov_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_FH_modificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> mov_FH_modificacion
		{
			get
			{
				return this._mov_FH_modificacion;
			}
			set
			{
				if ((this._mov_FH_modificacion != value))
				{
					this.Onmov_FH_modificacionChanging(value);
					this.SendPropertyChanging();
					this._mov_FH_modificacion = value;
					this.SendPropertyChanged("mov_FH_modificacion");
					this.Onmov_FH_modificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_usuario_modificacion", DbType="VarChar(25)")]
		public string mov_usuario_modificacion
		{
			get
			{
				return this._mov_usuario_modificacion;
			}
			set
			{
				if ((this._mov_usuario_modificacion != value))
				{
					this.Onmov_usuario_modificacionChanging(value);
					this.SendPropertyChanging();
					this._mov_usuario_modificacion = value;
					this.SendPropertyChanged("mov_usuario_modificacion");
					this.Onmov_usuario_modificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mov_estado", DbType="Int")]
		public System.Nullable<int> mov_estado
		{
			get
			{
				return this._mov_estado;
			}
			set
			{
				if ((this._mov_estado != value))
				{
					this.Onmov_estadoChanging(value);
					this.SendPropertyChanging();
					this._mov_estado = value;
					this.SendPropertyChanged("mov_estado");
					this.Onmov_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class usp_pmc_Solicitudes_CRUDResult
	{
		
		private string _Column1;
		
		public usp_pmc_Solicitudes_CRUDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
