//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int appID {
            get {
                return ((int)(this["appID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HBITTSQA; Initial Catalog=HQ400B;User=NTTRAIN1QA;Password=NTTRAIN1QA;" +
            "TrustServerCertificate=True")]
        public string TTS {
            get {
                return ((string)(this["TTS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESPRDSQL1V;Initial Catalog=ES_SOCKS;Integrated Security=True;TrustSer" +
            "verCertificate=True")]
        public string ESPRDSQL1V_ESSOCKS {
            get {
                return ((string)(this["ESPRDSQL1V_ESSOCKS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESPRDSQL1V;Initial Catalog=Tracer;Integrated Security=True;TrustServe" +
            "rCertificate=True")]
        public string TracerConnectionString {
            get {
                return ((string)(this["TracerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESPRDSQL1V;Initial Catalog=ES_SOCKS_StagingArea;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string ES_SOCKS_StagingAreaConnectionString {
            get {
                return ((string)(this["ES_SOCKS_StagingAreaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESPRDSQL1V;Initial Catalog=ES_SOCKS;Integrated Security=True;Persist " +
            "Security Info=False;MultipleActiveResultSets=True;Application Name=EntityFramewo" +
            "rk;TrustServerCertificate=True")]
        public string ES_SOCKSConnectionString {
            get {
                return ((string)(this["ES_SOCKSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ESPRDSQL1V;Initial Catalog=ES_SOCKS;Integrated Security=True;TrustSer" +
            "verCertificate=True")]
        public string ESDEVSQL1V_ESSOCKS {
            get {
                return ((string)(this["ESDEVSQL1V_ESSOCKS"]));
            }
        }
    }
}
