//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ES_SOCKSEntities2 : DbContext
    {
        public ES_SOCKSEntities2()
            : base("name=ES_SOCKSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mst_Applications> mst_Applications { get; set; }
        public virtual DbSet<mst_Autorizadores> mst_Autorizadores { get; set; }
        public virtual DbSet<mst_Autorizadores_Bitacora> mst_Autorizadores_Bitacora { get; set; }
        public virtual DbSet<mst_Objects> mst_Objects { get; set; }
        public virtual DbSet<wai_Ajuste> wai_Ajuste { get; set; }
        public virtual DbSet<wai_Areas> wai_Areas { get; set; }
        public virtual DbSet<wai_Bodegas> wai_Bodegas { get; set; }
        public virtual DbSet<wai_Defectos_NoConformes> wai_Defectos_NoConformes { get; set; }
        public virtual DbSet<wai_Devoluciones> wai_Devoluciones { get; set; }
        public virtual DbSet<wai_Factura> wai_Factura { get; set; }
        public virtual DbSet<wai_Factura_Detalle> wai_Factura_Detalle { get; set; }
        public virtual DbSet<wai_Inventario> wai_Inventario { get; set; }
        public virtual DbSet<wai_Inventario_Escaneos> wai_Inventario_Escaneos { get; set; }
        public virtual DbSet<wai_Inventario_Localidad> wai_Inventario_Localidad { get; set; }
        public virtual DbSet<wai_Item> wai_Item { get; set; }
        public virtual DbSet<wai_Item_Localidad> wai_Item_Localidad { get; set; }
        public virtual DbSet<wai_Localidad> wai_Localidad { get; set; }
        public virtual DbSet<wai_Pack_List> wai_Pack_List { get; set; }
        public virtual DbSet<wai_Parametros> wai_Parametros { get; set; }
        public virtual DbSet<wai_Plan> wai_Plan { get; set; }
        public virtual DbSet<wai_POS> wai_POS { get; set; }
        public virtual DbSet<wai_Prioridades> wai_Prioridades { get; set; }
        public virtual DbSet<wai_Proveedor> wai_Proveedor { get; set; }
        public virtual DbSet<wai_Solicitudes> wai_Solicitudes { get; set; }
        public virtual DbSet<wai_Tipo_Transaccion> wai_Tipo_Transaccion { get; set; }
        public virtual DbSet<wai_Transacciones> wai_Transacciones { get; set; }
        public virtual DbSet<wai_Transacciones_Devoluciones> wai_Transacciones_Devoluciones { get; set; }
    
        [DbFunction("ES_SOCKSEntities2", "fn_wai_Reporte_Toma_Inventario")]
        public virtual IQueryable<fn_wai_Reporte_Toma_Inventario_Result> fn_wai_Reporte_Toma_Inventario(Nullable<int> idInventario)
        {
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_wai_Reporte_Toma_Inventario_Result>("[ES_SOCKSEntities2].[fn_wai_Reporte_Toma_Inventario](@idInventario)", idInventarioParameter);
        }
    
        public virtual ObjectResult<usp_mst_PermissionsByUser_Result> usp_mst_PermissionsByUser(string usLogin, Nullable<int> app)
        {
            var usLoginParameter = usLogin != null ?
                new ObjectParameter("UsLogin", usLogin) :
                new ObjectParameter("UsLogin", typeof(string));
    
            var appParameter = app.HasValue ?
                new ObjectParameter("App", app) :
                new ObjectParameter("App", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_mst_PermissionsByUser_Result>("usp_mst_PermissionsByUser", usLoginParameter, appParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Areas_CRUD(string usuario, Nullable<int> id, string codigo, string descripcion, string accion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Areas_CRUD", usuarioParameter, idParameter, codigoParameter, descripcionParameter, accionParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Bodegas_CRUD(string usuario, Nullable<int> id, string nombre, string descripcion, string accion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Bodegas_CRUD", usuarioParameter, idParameter, nombreParameter, descripcionParameter, accionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_wai_Devoluciones_CRUD(string usuario, string accion, Nullable<int> itemID, Nullable<int> localidadID, Nullable<float> libras, string lote)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            var localidadIDParameter = localidadID.HasValue ?
                new ObjectParameter("localidadID", localidadID) :
                new ObjectParameter("localidadID", typeof(int));
    
            var librasParameter = libras.HasValue ?
                new ObjectParameter("libras", libras) :
                new ObjectParameter("libras", typeof(float));
    
            var loteParameter = lote != null ?
                new ObjectParameter("lote", lote) :
                new ObjectParameter("lote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_wai_Devoluciones_CRUD", usuarioParameter, accionParameter, itemIDParameter, localidadIDParameter, librasParameter, loteParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Factura_CRUD(string usuario, string accion, Nullable<int> idFactura, Nullable<int> idPO, string numero, Nullable<int> paquetes, Nullable<float> libras, Nullable<System.DateTime> fecha)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(int));
    
            var idPOParameter = idPO.HasValue ?
                new ObjectParameter("idPO", idPO) :
                new ObjectParameter("idPO", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var paquetesParameter = paquetes.HasValue ?
                new ObjectParameter("paquetes", paquetes) :
                new ObjectParameter("paquetes", typeof(int));
    
            var librasParameter = libras.HasValue ?
                new ObjectParameter("libras", libras) :
                new ObjectParameter("libras", typeof(float));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Factura_CRUD", usuarioParameter, accionParameter, idFacturaParameter, idPOParameter, numeroParameter, paquetesParameter, librasParameter, fechaParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Factura_Detalle_CRUD(string usuario, string accion, Nullable<int> idFacD, Nullable<int> idFactura, Nullable<int> idItem, Nullable<int> cantidad, Nullable<double> peso, string lote, Nullable<int> prioridad, Nullable<System.DateTime> fecha, Nullable<int> noConforme)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var idFacDParameter = idFacD.HasValue ?
                new ObjectParameter("idFacD", idFacD) :
                new ObjectParameter("idFacD", typeof(int));
    
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("idFactura", idFactura) :
                new ObjectParameter("idFactura", typeof(int));
    
            var idItemParameter = idItem.HasValue ?
                new ObjectParameter("idItem", idItem) :
                new ObjectParameter("idItem", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(double));
    
            var loteParameter = lote != null ?
                new ObjectParameter("lote", lote) :
                new ObjectParameter("lote", typeof(string));
    
            var prioridadParameter = prioridad.HasValue ?
                new ObjectParameter("prioridad", prioridad) :
                new ObjectParameter("prioridad", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var noConformeParameter = noConforme.HasValue ?
                new ObjectParameter("noConforme", noConforme) :
                new ObjectParameter("noConforme", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Factura_Detalle_CRUD", usuarioParameter, accionParameter, idFacDParameter, idFacturaParameter, idItemParameter, cantidadParameter, pesoParameter, loteParameter, prioridadParameter, fechaParameter, noConformeParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Inventario(string usuario, Nullable<int> idInventario, string periodo, string responsable, Nullable<System.DateTime> fecha)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var responsableParameter = responsable != null ?
                new ObjectParameter("responsable", responsable) :
                new ObjectParameter("responsable", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Inventario", usuarioParameter, idInventarioParameter, periodoParameter, responsableParameter, fechaParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Inventario_Escaneos(string usuario, string packID, Nullable<int> idInventario, Nullable<int> idLocalidad, Nullable<int> nuevo)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var packIDParameter = packID != null ?
                new ObjectParameter("packID", packID) :
                new ObjectParameter("packID", typeof(string));
    
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            var idLocalidadParameter = idLocalidad.HasValue ?
                new ObjectParameter("idLocalidad", idLocalidad) :
                new ObjectParameter("idLocalidad", typeof(int));
    
            var nuevoParameter = nuevo.HasValue ?
                new ObjectParameter("nuevo", nuevo) :
                new ObjectParameter("nuevo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Inventario_Escaneos", usuarioParameter, packIDParameter, idInventarioParameter, idLocalidadParameter, nuevoParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Inventario_Localidad(string usuario, string accion, Nullable<int> idInventario, Nullable<int> idLocalidad)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var idInventarioParameter = idInventario.HasValue ?
                new ObjectParameter("idInventario", idInventario) :
                new ObjectParameter("idInventario", typeof(int));
    
            var idLocalidadParameter = idLocalidad.HasValue ?
                new ObjectParameter("idLocalidad", idLocalidad) :
                new ObjectParameter("idLocalidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Inventario_Localidad", usuarioParameter, accionParameter, idInventarioParameter, idLocalidadParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Item_CRUD(string usuario, Nullable<int> id, Nullable<int> bodega, string codigo, string descripcion, string accion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bodegaParameter = bodega.HasValue ?
                new ObjectParameter("bodega", bodega) :
                new ObjectParameter("bodega", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Item_CRUD", usuarioParameter, idParameter, bodegaParameter, codigoParameter, descripcionParameter, accionParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Localidades_CRUD(string usuario, Nullable<int> id, string nombre, string accion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Localidades_CRUD", usuarioParameter, idParameter, nombreParameter, accionParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_POS_CRUD(string usuario, string accion, Nullable<int> idPO, string numeroPO, Nullable<int> proveedorID, Nullable<int> bodegaID, Nullable<int> estado, string semana, Nullable<System.DateTime> fecha, string creador)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var idPOParameter = idPO.HasValue ?
                new ObjectParameter("idPO", idPO) :
                new ObjectParameter("idPO", typeof(int));
    
            var numeroPOParameter = numeroPO != null ?
                new ObjectParameter("numeroPO", numeroPO) :
                new ObjectParameter("numeroPO", typeof(string));
    
            var proveedorIDParameter = proveedorID.HasValue ?
                new ObjectParameter("proveedorID", proveedorID) :
                new ObjectParameter("proveedorID", typeof(int));
    
            var bodegaIDParameter = bodegaID.HasValue ?
                new ObjectParameter("bodegaID", bodegaID) :
                new ObjectParameter("bodegaID", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var semanaParameter = semana != null ?
                new ObjectParameter("semana", semana) :
                new ObjectParameter("semana", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var creadorParameter = creador != null ?
                new ObjectParameter("creador", creador) :
                new ObjectParameter("creador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_POS_CRUD", usuarioParameter, accionParameter, idPOParameter, numeroPOParameter, proveedorIDParameter, bodegaIDParameter, estadoParameter, semanaParameter, fechaParameter, creadorParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Prioridades_CRUD(string usuario, string accion, Nullable<int> item, string lote, string semana, Nullable<int> prioridad)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            var itemParameter = item.HasValue ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(int));
    
            var loteParameter = lote != null ?
                new ObjectParameter("lote", lote) :
                new ObjectParameter("lote", typeof(string));
    
            var semanaParameter = semana != null ?
                new ObjectParameter("semana", semana) :
                new ObjectParameter("semana", typeof(string));
    
            var prioridadParameter = prioridad.HasValue ?
                new ObjectParameter("prioridad", prioridad) :
                new ObjectParameter("prioridad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Prioridades_CRUD", usuarioParameter, accionParameter, itemParameter, loteParameter, semanaParameter, prioridadParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Proveedores_CRUD(string usuario, Nullable<int> id, string nombre, string accion)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Proveedores_CRUD", usuarioParameter, idParameter, nombreParameter, accionParameter);
        }
    
        public virtual ObjectResult<usp_wai_Reporte_Entradas_Salidas_Result> usp_wai_Reporte_Entradas_Salidas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> reporte, Nullable<int> bodega)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var reporteParameter = reporte.HasValue ?
                new ObjectParameter("reporte", reporte) :
                new ObjectParameter("reporte", typeof(int));
    
            var bodegaParameter = bodega.HasValue ?
                new ObjectParameter("bodega", bodega) :
                new ObjectParameter("bodega", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_wai_Reporte_Entradas_Salidas_Result>("usp_wai_Reporte_Entradas_Salidas", fechaInicioParameter, fechaFinParameter, reporteParameter, bodegaParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Solicitud_CRUD(Nullable<int> id, string semana, string sol_item, string sol_estado, string sol_UOM, Nullable<int> sol_pro_ID, string sol_localidad, string sol_prioridad, string sol_usuario_pedido, string accion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var semanaParameter = semana != null ?
                new ObjectParameter("semana", semana) :
                new ObjectParameter("semana", typeof(string));
    
            var sol_itemParameter = sol_item != null ?
                new ObjectParameter("sol_item", sol_item) :
                new ObjectParameter("sol_item", typeof(string));
    
            var sol_estadoParameter = sol_estado != null ?
                new ObjectParameter("sol_estado", sol_estado) :
                new ObjectParameter("sol_estado", typeof(string));
    
            var sol_UOMParameter = sol_UOM != null ?
                new ObjectParameter("sol_UOM", sol_UOM) :
                new ObjectParameter("sol_UOM", typeof(string));
    
            var sol_pro_IDParameter = sol_pro_ID.HasValue ?
                new ObjectParameter("sol_pro_ID", sol_pro_ID) :
                new ObjectParameter("sol_pro_ID", typeof(int));
    
            var sol_localidadParameter = sol_localidad != null ?
                new ObjectParameter("sol_localidad", sol_localidad) :
                new ObjectParameter("sol_localidad", typeof(string));
    
            var sol_prioridadParameter = sol_prioridad != null ?
                new ObjectParameter("sol_prioridad", sol_prioridad) :
                new ObjectParameter("sol_prioridad", typeof(string));
    
            var sol_usuario_pedidoParameter = sol_usuario_pedido != null ?
                new ObjectParameter("sol_usuario_pedido", sol_usuario_pedido) :
                new ObjectParameter("sol_usuario_pedido", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Solicitud_CRUD", idParameter, semanaParameter, sol_itemParameter, sol_estadoParameter, sol_UOMParameter, sol_pro_IDParameter, sol_localidadParameter, sol_prioridadParameter, sol_usuario_pedidoParameter, accionParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Transacciones_CRUD(string usuario, Nullable<int> accion, string packID, Nullable<float> libras, Nullable<int> itemID, Nullable<int> autoriza)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(int));
    
            var packIDParameter = packID != null ?
                new ObjectParameter("packID", packID) :
                new ObjectParameter("packID", typeof(string));
    
            var librasParameter = libras.HasValue ?
                new ObjectParameter("libras", libras) :
                new ObjectParameter("libras", typeof(float));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            var autorizaParameter = autoriza.HasValue ?
                new ObjectParameter("Autoriza", autoriza) :
                new ObjectParameter("Autoriza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Transacciones_CRUD", usuarioParameter, accionParameter, packIDParameter, librasParameter, itemIDParameter, autorizaParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_TransaccionesProv_CRUD(string usuario, Nullable<int> accion, string packProvID, Nullable<float> libras, Nullable<int> itemID, Nullable<int> autoriza)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var accionParameter = accion.HasValue ?
                new ObjectParameter("accion", accion) :
                new ObjectParameter("accion", typeof(int));
    
            var packProvIDParameter = packProvID != null ?
                new ObjectParameter("packProvID", packProvID) :
                new ObjectParameter("packProvID", typeof(string));
    
            var librasParameter = libras.HasValue ?
                new ObjectParameter("libras", libras) :
                new ObjectParameter("libras", typeof(float));
    
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("itemID", itemID) :
                new ObjectParameter("itemID", typeof(int));
    
            var autorizaParameter = autoriza.HasValue ?
                new ObjectParameter("Autoriza", autoriza) :
                new ObjectParameter("Autoriza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_TransaccionesProv_CRUD", usuarioParameter, accionParameter, packProvIDParameter, librasParameter, itemIDParameter, autorizaParameter);
        }
    
        public virtual ObjectResult<string> usp_wai_Traslados(string usuario, Nullable<int> packID, Nullable<int> idLocalidad, Nullable<int> origen)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var packIDParameter = packID.HasValue ?
                new ObjectParameter("PackID", packID) :
                new ObjectParameter("PackID", typeof(int));
    
            var idLocalidadParameter = idLocalidad.HasValue ?
                new ObjectParameter("idLocalidad", idLocalidad) :
                new ObjectParameter("idLocalidad", typeof(int));
    
            var origenParameter = origen.HasValue ?
                new ObjectParameter("origen", origen) :
                new ObjectParameter("origen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_wai_Traslados", usuarioParameter, packIDParameter, idLocalidadParameter, origenParameter);
        }
    }
}
