//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_Applications()
        {
            this.mst_Objects = new HashSet<mst_Objects>();
        }
    
        public int App_ID { get; set; }
        public string App_Name { get; set; }
        public string App_Description { get; set; }
        public System.DateTime App_DT { get; set; }
        public int Dept_ID { get; set; }
        public string App_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Objects> mst_Objects { get; set; }
    }
}
