//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_Objects()
        {
            this.mst_Objects1 = new HashSet<mst_Objects>();
        }
    
        public int Obj_ID { get; set; }
        public int App_ID { get; set; }
        public string Obj_Name { get; set; }
        public string Obj_Description { get; set; }
        public string Obj_Type { get; set; }
        public Nullable<int> Obj_Parent { get; set; }
        public System.DateTime Obj_DT { get; set; }
    
        public virtual mst_Applications mst_Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Objects> mst_Objects1 { get; set; }
        public virtual mst_Objects mst_Objects2 { get; set; }
    }
}
