//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Autorizadores
    {
        public int aut_ID { get; set; }
        public Nullable<int> aut_Obj_ID { get; set; }
        public string aut_usuario { get; set; }
        public string aut_contrasenia { get; set; }
        public Nullable<System.DateTime> aut_FH_creacion { get; set; }
        public Nullable<bool> aut_estado { get; set; }
    }
}
