//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Inventario_Escaneos
    {
        public int inve_id { get; set; }
        public int inve_localidadinventario_id { get; set; }
        public string inve_packid { get; set; }
        public Nullable<float> inve_libras { get; set; }
        public Nullable<int> inve_escaneado { get; set; }
        public Nullable<int> inve_localidad_preescaneo { get; set; }
        public Nullable<int> inve_nuevo { get; set; }
        public Nullable<int> inve_eliminado { get; set; }
        public string inve_usuario_crea { get; set; }
        public Nullable<System.DateTime> inve_DT_crea { get; set; }
        public string inve_usuario_mod { get; set; }
        public Nullable<System.DateTime> inve_DT_mod { get; set; }
    }
}
