//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Factura()
        {
            this.wai_Factura_Detalle = new HashSet<wai_Factura_Detalle>();
        }
    
        public int fac_id { get; set; }
        public int fac_pos_id { get; set; }
        public string fac_numero { get; set; }
        public Nullable<int> fac_paquetes { get; set; }
        public Nullable<float> fac_libras { get; set; }
        public Nullable<System.DateTime> fac_fecha { get; set; }
        public string fac_usuario_crea { get; set; }
        public Nullable<System.DateTime> fac_fecha_crea { get; set; }
        public string fac_usuario_mod { get; set; }
        public Nullable<System.DateTime> fac_fecha_mod { get; set; }
        public string fac_medida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Factura_Detalle> wai_Factura_Detalle { get; set; }
        public virtual wai_POS wai_POS { get; set; }
    }
}
