//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Inventario()
        {
            this.wai_Inventario_Localidad = new HashSet<wai_Inventario_Localidad>();
        }
    
        public int inv_id { get; set; }
        public string inv_periodo { get; set; }
        public string inv_responsable { get; set; }
        public Nullable<System.DateTime> inv_fecha { get; set; }
        public Nullable<int> inv_activo { get; set; }
        public string inv_usuario_crea { get; set; }
        public Nullable<System.DateTime> inv_fecha_crea { get; set; }
        public string inv_usuario_mod { get; set; }
        public Nullable<System.DateTime> inv_fecha_mod { get; set; }
        public Nullable<int> bod_id { get; set; }
        public Nullable<int> inv_tipo { get; set; }
        public Nullable<int> inv_year { get; set; }
        public Nullable<int> inv_num_periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Inventario_Localidad> wai_Inventario_Localidad { get; set; }
    }
}
