//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Proveedor()
        {
            this.wai_POS = new HashSet<wai_POS>();
            this.wai_Solicitudes = new HashSet<wai_Solicitudes>();
        }
    
        public int pro_id { get; set; }
        public string pro_nombre { get; set; }
        public string pro_usuario_crea { get; set; }
        public Nullable<System.DateTime> pro_fecha_crea { get; set; }
        public string pro_usuario_mod { get; set; }
        public Nullable<System.DateTime> pro_fecha_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_POS> wai_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Solicitudes> wai_Solicitudes { get; set; }
    }
}
