//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Prioridades
    {
        public int pri_id { get; set; }
        public Nullable<int> pri_item_id { get; set; }
        public string pri_lote { get; set; }
        public string pri_semana { get; set; }
        public Nullable<int> pri_prioridad { get; set; }
        public Nullable<int> pri_paquetes { get; set; }
        public Nullable<float> pri_libras { get; set; }
        public string pri_usuario_crea { get; set; }
        public Nullable<System.DateTime> pri_fecha_crea { get; set; }
        public string pri_usuario_mod { get; set; }
        public Nullable<System.DateTime> pri_fecha_mod { get; set; }
    
        public virtual wai_Item wai_Item { get; set; }
    }
}
