//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Devoluciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Devoluciones()
        {
            this.wai_Transacciones_Devoluciones = new HashSet<wai_Transacciones_Devoluciones>();
        }
    
        public int dev_id { get; set; }
        public int dev_item_id { get; set; }
        public Nullable<int> dev_localidad_id { get; set; }
        public string dev_codigo { get; set; }
        public Nullable<float> dev_libras { get; set; }
        public string dev_lote { get; set; }
        public Nullable<int> dev_prioridad { get; set; }
        public Nullable<System.DateTime> dev_fecha_in { get; set; }
        public Nullable<System.DateTime> dev_fecha_out { get; set; }
        public Nullable<System.DateTime> dev_fecha_produccion { get; set; }
        public Nullable<System.DateTime> dev_fecha_caducidad { get; set; }
        public Nullable<float> dev_libras_out { get; set; }
        public Nullable<int> dev_impreso { get; set; }
        public string dev_usuario_crea { get; set; }
        public Nullable<System.DateTime> dev_fecha_crea { get; set; }
        public Nullable<bool> dev_No_Conformidad { get; set; }
        public Nullable<int> def_ID { get; set; }
        public Nullable<System.DateTime> dev_FH_No_Conforme_IN { get; set; }
        public Nullable<System.DateTime> dev_FH_No_Conforme_OUT { get; set; }
        public Nullable<int> pro_id { get; set; }
    
        public virtual wai_Defectos_NoConformes wai_Defectos_NoConformes { get; set; }
        public virtual wai_Item wai_Item { get; set; }
        public virtual wai_Localidad wai_Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Transacciones_Devoluciones> wai_Transacciones_Devoluciones { get; set; }
    }
}
