//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Item_Localidad
    {
        public int itl_id { get; set; }
        public Nullable<int> itl_localidad_id { get; set; }
        public Nullable<int> itl_item_id { get; set; }
        public string itl_periodo { get; set; }
        public string itl_usuario_crea { get; set; }
        public Nullable<System.DateTime> itl_fecha_crea { get; set; }
        public string itl_usuario_mod { get; set; }
        public Nullable<System.DateTime> itl_fecha_mod { get; set; }
    }
}
