//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Bodegas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Bodegas()
        {
            this.wai_Item = new HashSet<wai_Item>();
            this.wai_POS = new HashSet<wai_POS>();
        }
    
        public int bod_id { get; set; }
        public string bod_nombre { get; set; }
        public string bod_descripcion { get; set; }
        public string bod_usuario_crea { get; set; }
        public Nullable<System.DateTime> bod_fecha_crea { get; set; }
        public string bod_usuario_mod { get; set; }
        public Nullable<System.DateTime> bod_fecha_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Item> wai_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_POS> wai_POS { get; set; }
    }
}
