//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Transacciones
    {
        public int tra_id { get; set; }
        public Nullable<int> tra_pack_list_id { get; set; }
        public Nullable<int> tra_tipo_transaccion { get; set; }
        public Nullable<float> tra_libras { get; set; }
        public string tra_usuario { get; set; }
        public System.DateTime tra_DT { get; set; }
    
        public virtual wai_Pack_List wai_Pack_List { get; set; }
        public virtual wai_Tipo_Transaccion wai_Tipo_Transaccion { get; set; }
    }
}
