//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_POS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_POS()
        {
            this.wai_Factura = new HashSet<wai_Factura>();
        }
    
        public int pos_id { get; set; }
        public string pos_numero { get; set; }
        public Nullable<int> pos_proveedor_id { get; set; }
        public Nullable<int> pos_bodega_id { get; set; }
        public Nullable<bool> pos_ajuste { get; set; }
        public string pos_estado { get; set; }
        public string pos_semana { get; set; }
        public Nullable<System.DateTime> pos_fecha { get; set; }
        public string pos_creador { get; set; }
    
        public virtual wai_Bodegas wai_Bodegas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Factura> wai_Factura { get; set; }
        public virtual wai_Proveedor wai_Proveedor { get; set; }
    }
}
