//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Pack_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Pack_List()
        {
            this.wai_Transacciones = new HashSet<wai_Transacciones>();
        }
    
        public int pac_id { get; set; }
        public Nullable<int> pac_factura_detalle_id { get; set; }
        public Nullable<int> pac_localidad_id { get; set; }
        public string pac_prov_pack_id { get; set; }
        public Nullable<float> pac_libras { get; set; }
        public Nullable<bool> pac_impreso { get; set; }
        public Nullable<System.DateTime> pac_scan_whin { get; set; }
        public Nullable<System.DateTime> pac_scan_whout { get; set; }
        public Nullable<float> pac_libras_salida { get; set; }
        public Nullable<bool> pac_ajuste { get; set; }
        public Nullable<System.DateTime> pac_fecha_produccion { get; set; }
        public Nullable<int> pac_envio { get; set; }
        public string pac_usuario_crea { get; set; }
        public Nullable<System.DateTime> pac_fecha_crea { get; set; }
        public string pac_usuario_mod { get; set; }
        public Nullable<System.DateTime> pac_fecha_mod { get; set; }
        public Nullable<bool> pac_No_Conformidad { get; set; }
        public Nullable<int> def_ID { get; set; }
        public Nullable<System.DateTime> pac_FH_No_Conforme_IN { get; set; }
        public Nullable<System.DateTime> pac_FH_No_Conforme_OUT { get; set; }
    
        public virtual wai_Defectos_NoConformes wai_Defectos_NoConformes { get; set; }
        public virtual wai_Factura_Detalle wai_Factura_Detalle { get; set; }
        public virtual wai_Localidad wai_Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Transacciones> wai_Transacciones { get; set; }
    }
}
