//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Item()
        {
            this.wai_Devoluciones = new HashSet<wai_Devoluciones>();
            this.wai_Factura_Detalle = new HashSet<wai_Factura_Detalle>();
            this.wai_Prioridades = new HashSet<wai_Prioridades>();
        }
    
        public int ite_id { get; set; }
        public Nullable<int> ite_bodega_id { get; set; }
        public Nullable<int> ite_area_id { get; set; }
        public string ite_codigo { get; set; }
        public string ite_descripcion { get; set; }
        public Nullable<int> ite_existencia { get; set; }
        public string ite_usuario_crea { get; set; }
        public Nullable<System.DateTime> ite_fecha_crea { get; set; }
        public string ite_usuario_mod { get; set; }
        public Nullable<System.DateTime> ite_fecha_mod { get; set; }
    
        public virtual wai_Areas wai_Areas { get; set; }
        public virtual wai_Bodegas wai_Bodegas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Devoluciones> wai_Devoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Factura_Detalle> wai_Factura_Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Prioridades> wai_Prioridades { get; set; }
    }
}
