//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Solicitudes
    {
        public int sol_ID { get; set; }
        public string sol_semana { get; set; }
        public string sol_item { get; set; }
        public string sol_estado { get; set; }
        public string sol_UOM { get; set; }
        public int sol_pro_ID { get; set; }
        public string sol_turno_crea { get; set; }
        public string sol_turno_entrega { get; set; }
        public System.DateTime sol_FH_crea { get; set; }
        public Nullable<System.DateTime> sol_FH_entrega { get; set; }
        public string sol_localidad { get; set; }
        public string sol_prioridad { get; set; }
        public string sol_usuario_pedido { get; set; }
        public string sol_usuario_entrega { get; set; }
        public Nullable<int> sol_aut_ID { get; set; }
        public string sol_pack_list_ID { get; set; }
    
        public virtual wai_Plan wai_Plan { get; set; }
        public virtual wai_Proveedor wai_Proveedor { get; set; }
    }
}
