//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Transacciones_Devoluciones
    {
        public int tra_dev_id { get; set; }
        public Nullable<int> tra_dev_dev_id { get; set; }
        public Nullable<int> tra_dev_tipo_transaccion { get; set; }
        public Nullable<float> tra_dev_libras { get; set; }
        public string tra_dev_usuario { get; set; }
        public Nullable<System.DateTime> tra_dev_DT { get; set; }
    
        public virtual wai_Devoluciones wai_Devoluciones { get; set; }
        public virtual wai_Tipo_Transaccion wai_Tipo_Transaccion { get; set; }
    }
}
