//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Localidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Localidad()
        {
            this.wai_Devoluciones = new HashSet<wai_Devoluciones>();
            this.wai_Inventario_Localidad = new HashSet<wai_Inventario_Localidad>();
            this.wai_Pack_List = new HashSet<wai_Pack_List>();
        }
    
        public int loc_id { get; set; }
        public string loc_nombre { get; set; }
        public string loc_usuario_crea { get; set; }
        public Nullable<System.DateTime> loc_fecha_crea { get; set; }
        public string loc_usuario_mod { get; set; }
        public Nullable<System.DateTime> loc_fecha_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Devoluciones> wai_Devoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Inventario_Localidad> wai_Inventario_Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Pack_List> wai_Pack_List { get; set; }
    }
}
