//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Factura_Detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Factura_Detalle()
        {
            this.wai_Pack_List = new HashSet<wai_Pack_List>();
        }
    
        public int facd_id { get; set; }
        public int facd_fac_id { get; set; }
        public int facd_item_id { get; set; }
        public Nullable<int> facd_cantidad { get; set; }
        public Nullable<double> facd_peso { get; set; }
        public string facd_lote { get; set; }
        public Nullable<int> facd_prioridad { get; set; }
        public Nullable<System.DateTime> facd_fecha_caducidad { get; set; }
        public Nullable<int> facd_no_conforme { get; set; }
        public string facd_usuario_crea { get; set; }
        public Nullable<System.DateTime> facd_fecha_crea { get; set; }
        public string facd_usuario_mod { get; set; }
        public Nullable<System.DateTime> facd_fecha_mod { get; set; }
    
        public virtual wai_Factura wai_Factura { get; set; }
        public virtual wai_Item wai_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Pack_List> wai_Pack_List { get; set; }
    }
}
