//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Ajuste
    {
        public int aju_id { get; set; }
        public Nullable<int> aju_pack_id { get; set; }
        public Nullable<System.DateTime> aju_fecha_antigua { get; set; }
        public string aju_tipo_ajuste { get; set; }
        public Nullable<System.DateTime> aju_fecha_ajuste { get; set; }
        public string aju_usuario_crea { get; set; }
        public Nullable<System.DateTime> aju_fecha_crea { get; set; }
    }
}
