//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Inventario_Localidad
    {
        public int invl_id { get; set; }
        public int invl_inventario_id { get; set; }
        public int invl_localidad_id { get; set; }
        public string invl_usuario_crea { get; set; }
        public Nullable<System.DateTime> invl_fecha_crea { get; set; }
        public string invl_usuario_mod { get; set; }
        public Nullable<System.DateTime> invl_fecha_mod { get; set; }
        public string invl_responsable { get; set; }
    
        public virtual wai_Inventario wai_Inventario { get; set; }
        public virtual wai_Localidad wai_Localidad { get; set; }
    }
}
