//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rmc.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class wai_Areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wai_Areas()
        {
            this.wai_Item = new HashSet<wai_Item>();
        }
    
        public int are_id { get; set; }
        public string are_codigo { get; set; }
        public string are_descripcion { get; set; }
        public string are_usuario_crea { get; set; }
        public Nullable<System.DateTime> are_fecha_crea { get; set; }
        public string are_usuario_mod { get; set; }
        public Nullable<System.DateTime> are_fecha_mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wai_Item> wai_Item { get; set; }
    }
}
